apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kuberlogic-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlogic-operator
  namespace: system
  labels:
    control-plane: kuberlogic-operator
spec:
  selector:
    matchLabels:
      control-plane: kuberlogic-operator
  replicas: 1
  template:
    metadata:
      annotations:
        monitoring.cloudlinux.com/port: "8443"
        monitoring.cloudlinux.com/scrape: "true"
        monitoring.cloudlinux.com/scheme: "https"
      labels:
        control-plane: kuberlogic-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - command:
          - /apiserver
        args:
          - --scheme=http
        image: apiserver:latest
        name: apiserver
        ports:
          - containerPort: 8001
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
