---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-kla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-kla
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-kla
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicalerts
      - kuberlogicalerts/status
      - kuberlogicalerts/finalizer
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicservices
    verbs:
      - get