---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-kls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-kls
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-kls
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicservices
      - kuberlogicservices/status
      - kuberlogicservices/finalizer
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - mysql.presslabs.org
    resources:
      - mysqlclusters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - acid.zalan.do
    resources:
      - postgresqls
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - list
      - watch