---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-klt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-klt
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-klt
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogictenants
      - kuberlogictenants/status
      - kuberlogictenants/finalizer
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
      - serviceaccounts
    verbs:
      - get
      - create
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - list
      - watch
      - update
      - patch
  # permissions that operator grants to tenants
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list