apiVersion: v1
data:
  config.js: "let configApiUrl = '{{ .Values.config.apiEndpoint }}/api/v1';\r\n"
kind: ConfigMap
metadata:
  name: "{{ include "kuberlogic-ui.fullname" . }}"
  namespace: {{ .Release.Namespace }}
