apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuberlogic-ui.fullname" . }}
  labels:
    {{- include "kuberlogic-ui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kuberlogic-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kuberlogic-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kuberlogic-ui.serviceAccountName" . }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
            - key: config.js
              path: config.js
          name: {{ include  "kuberlogic-ui.fullname" . }}
        name: kl-ui-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config.js
              name: kl-ui-config
              subPath: config.js