{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "kuberlogic-ui.fullname" . }}"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kuberlogic-ui.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{ end }}