
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kuberlogic-com-v1-kuberlogicservice
  failurePolicy: Fail
  name: mkuberlogicservice.kuberlogic.com
  rules:
  - apiGroups:
    - kuberlogic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuberlogicservices
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kuberlogic-com-v1-kuberlogicservice
  failurePolicy: Fail
  name: vkuberlogicservice.kuberlogic.com
  rules:
  - apiGroups:
    - kuberlogic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuberlogicservices
  sideEffects: None
