{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "apiserver.fullname" . }}"
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "apiserver.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}