apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiserver.serviceAccountName" . }}
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicservices
      - kuberlogicbackupschedules
      - kuberlogicbackuprestores
      - kuberlogictenants
    verbs:
      - create
      - delete
      - update
      - watch
      - list
      - patch
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
      - get
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apiserver.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apiserver.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "apiserver.serviceAccountName" . }}