apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../crd
  - ../rbac
  - ../operators/postgresql/zalando
  - ../operators/mysql/presslabs
  - ../keycloak
  - ../webhook


namespace: default
namePrefix: cm-