---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicservices
      - kuberlogicbackupschedules
      - kuberlogicbackuprestores
      - kuberlogictenants
      - kuberlogicalerts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - acid.zalan.do
    resources:
      - postgresqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mysql.presslabs.org
    resources:
      - mysqlclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogicservices/status
      - kuberlogicbackupschedules/status
      - kuberlogicbackuprestores/status
      - kuberlogictenants/status
      - kuberlogicalerts/status
    verbs:
      - get
      - patch
      - update
  # for backups:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - list
      - get
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - services
      - pods/log
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # for kuberlogictenants
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
      - secrets
    verbs:
      - create
      - patch
      - update
      - list
      - watch
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - patch
      - update
      - list
      - watch
      - get
  # permissions operator will grant to tenant service accounts
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list