apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: postgres-operator
    newName: quay.io/kuberlogic/postgres-operator
    newTag: v1.6.2
patchesStrategicMerge:
  - patches/regcred.yaml
resources:
  - configmap.yaml
  - operator-service-account-rbac.yaml
  - deployment.yaml
  - api-service.yaml

