# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kuberlogicservices.kuberlogic.com
spec:
  # The CustomResourceDefinition "kuberlogicservices.kuberlogic.com" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
#  preserveUnknownFields: false
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        service:
          namespace: system
          name: webhook-service
          path: /convert
#    webhookClientConfig:
#      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
#      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
#      caBundle: Cg==
#      service:
#        namespace: system
#        name: webhook-service
#        path: /convert
