apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
        - name: keycloak-operator
          # Replace this with the built image name
          image: quay.io/kuberlogic/keycloak-operator:master-23-04-2021
          command:
            - keycloak-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator"
            - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
              value: quay.io/kuberlogic/keycloak-init-container:master
            - name: RELATED_IMAGE_POSTGRESQL
              value: quay.io/kuberlogic/keycloak-postgresql-10-rhel7:1
