---
apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default'
    receivers:
      - name: 'default'
        webhook_configs:
        - url: 'http://localhost:{{ .Values.alertreceiver.port }}/'
kind: ConfigMap
metadata:
  name: {{ .Values.alertmanager.configmap }}
  namespace: {{ .Release.Namespace }}