{{ if .Values.eagle.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ .Values.eagle.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
  name: kube-eagle
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
  name: kube-eagle
subjects:
  - kind: ServiceAccount
    name: {{ .Values.eagle.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eagle
---
apiVersion: v1
kind: Service
metadata:
  name: kube-eagle
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.eagle.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-eagle
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kube-eagle
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kube-eagle
      {{- include "monitoring.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kube-eagle
        {{- include "monitoring.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccountName: {{ .Values.eagle.serviceAccount.name }}
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8  }}
      {{ end }}
      containers:
        - name: kube-eagle
          image: "{{ .Values.eagle.image.repository }}:{{ .Values.eagle.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TELEMETRY_HOST
              value: "127.0.0.1"
            - name: TELEMETRY_PORT
              value: "{{ .Values.eagle.port }}"
            - name: METRICS_NAMESPACE
              value: "eagle"
            - name: LOG_LEVEL
              value: "info"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:{{ .Values.eagle.port }}/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
{{ end }}