---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-eagle
  name: sa-kube-eagle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-eagle
  name: kube-eagle
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-eagle
  name: kube-eagle
subjects:
  - kind: ServiceAccount
    name: sa-kube-eagle
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eagle
---
apiVersion: v1
kind: Service
metadata:
  name: kube-eagle
  labels:
    app.kubernetes.io/name: kube-eagle
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kube-eagle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-eagle
  labels:
    app.kubernetes.io/name: kube-eagle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-eagle
  template:
    metadata:
      annotations:
        monitoring.cloudlinux.com/scrape: "true"
        monitoring.cloudlinux.com/port: "8443"
        monitoring.cloudlinux.com/scheme: "https"
      labels:
        app.kubernetes.io/name: kube-eagle
    spec:
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccountName: sa-kube-eagle
      containers:
        - name: kube-eagle
          image: quay.io/kuberlogic/kube-eagle:1.1.4
          imagePullPolicy: IfNotPresent
          env:
            - name: TELEMETRY_HOST
              value: "127.0.0.1"
            - name: TELEMETRY_PORT
              value: "8080"
            - name: METRICS_NAMESPACE
              value: "eagle"
            - name: LOG_LEVEL
              value: "info"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: quay.io/kuberlogic/kube-rbac-proxy:v0.5.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi