name: Release

on:
  push:
    branches:
      - KL-137
#  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.19.0'
          kubernetes version: 'v1.20.5'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure logs
        working-directory: ./modules/apiserver/tests
        run: |
          echo Your testid label value is $GITHUB_RUN_ID
          make configure-logs
        env:
          LOGZ_IO_TOKEN: ${{ secrets.LOGZ_IO_TOKEN }}
          LOGZ_IO_LISTENER: ${{ secrets.LOGZ_IO_LISTENER }}

      - name: Create secret of operator
        run: |
          kubectl create secret docker-registry kuberlogic-registry --docker-server=$REGISTRY_SERVER --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_PASSWORD
        env:
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build the new images
        run: |
          make docker-build

      - name: Deploy operator
        run: |
          make install
          make deploy

      - name: Setup minio for backup storage
        working-directory: ./modules/apiserver/tests
        run: |
          make deploy-minio

      - name: Waiting ready the pods
        run: |
          kubectl wait --for=condition=Ready pods --all --timeout=5m

      - name: Show pod status
        run: |
          kubectl logs -l app=minio
          docker images
        if: ${{ failure() }}

      - name: Create test bucket (backup storage)
        working-directory: ./modules/apiserver/tests
        run: |
          make create-bucket

      - name: Ensure keycloak is ready
        working-directory: ./modules/apiserver/tests/config
        run: |
          ./wait-for-keycloak.sh

      - name: Run the remote tests
        working-directory: ./modules/apiserver/tests
        run: |
          make remote-test RUN=TestService/mysql

      - name: Push the new images
        run: |
          docker login --username=$REGISTRY_USER --password=$REGISTRY_PASSWORD $REGISTRY_SERVER
          make docker-push
        env:
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

#      - name: Release
#        uses: docker://antonyurchenko/git-release:v4.1.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PRE_RELEASE: true
#        with:
#          args: |
#            linux-amd64.zip

      - name: Show status
        run: |
          kubectl get pod,sts,deploy,svc,cj,job -o yaml
        if: ${{ failure() }}

      - name: Generating logs
        working-directory: ./modules/apiserver/tests
        run: |
          kubectl logs -l control-plane=kuberlogic-operator -c manager --tail=-1 > kuberlogic-operator.log
          kubectl logs -l control-plane=kuberlogic-operator -c apiserver --tail=-1 > kuberlogic-apiserver.log

          kubectl logs -l name=postgres-operator --tail=-1 > postgres-operator.log
          kubectl logs -l app=mysql-operator -c mysql-operator --tail=-1 > mysql-operator.log
          kubectl describe pod -l name=postgres-operator > postgres-operator.describe.log
          kubectl describe pod -l app=mysql-operator > mysql-operator.describe.log
          kubectl describe pod -l app=alertmanager > alertmanager.describe.log
          kubectl get pod --all-namespaces > pods-status.log
          kubectl get endpoints --all-namespaces > endpoints.log
          kubectl get services --all-namespaces > services.log
          kubectl logs -l app.kubernetes.io/name=kube-state-metrics -c kube-state-metrics > kube-state-metrics.logs
          kubectl logs -l app.kubernetes.io/name=kube-state-metrics -c kube-rbac-proxy > kube-rbac-proxy.kube-state-metrics.logs
          kubectl get kuberlogicservice,kuberlogicbackupschedules,kuberlogicbackuprestores --all-namespaces > kuberlogics-services.log
          kubectl describe pod -l app.kubernetes.io/name=mysql --all-namespaces > mysql-cluster.describe.log
          kubectl describe pod -l application=spilo --all-namespaces > pg-cluster.describe.log
          kubectl logs -l app.kubernetes.io/name=mysql -c mysql --tail=-1 > mysql-cluster.log
          kubectl logs -l application=spilo -c postgres --tail=-1 > pg-cluster.log
        if: ${{ always() }}
        continue-on-error: true

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            ./modules/apiserver/tests/*.log
        if: ${{ always() }}
