apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: updater
  newName: quay.io/kuberlogic/updater
<<<<<<< HEAD
  newTag: 0.0.27
=======
  newTag: 0.0.26
>>>>>>> master
patchesStrategicMerge:
- patches/regcred.yaml
- patches/gitlab-env.yaml
resources:
- cronjob.yaml
- service-account-rbac.yaml
