---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberlogic-updater
  labels:
    app: kuberlogic-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberlogic-updater
  labels:
    app: kuberlogic-updater
rules:
  - apiGroups:
      - kuberlogic.com
    resources:
      - kuberlogics
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberlogic-updater
  labels:
    app: kuberlogic-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberlogic-updater
subjects:
  - name: kuberlogic-updater
#    namespace: default
    kind: ServiceAccount