---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: kuberlogic-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
  {{ toYaml .Values.labels | nindent 4 }}
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: False
  podDisruptionBudget:
    enabled: False
  externalDatabase:
    enabled: False
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: kuberlogic
  namespace: {{ .Release.Namespace }}
  labels:
  {{ toYaml .Values.labels | nindent 4 }}
spec:
  realm:
    id: "{{ .Values.realm.id }}"
    realm: "{{ .Values.realm.name }}"
    accessTokenLifespan: 3600
    accessTokenLifespanForImplicitFlow: 3600
    registrationAllowed: false
    enabled: true
    displayName: "Kuberlogic"
    eventsListeners:
      - "metrics-listener"
    userManagedAccessAllowed: true
    users:
      - username: "{{ .Values.realm.name }}"
        firstName: "Kuberlogic"
        lastName: "Realm"
        email: "realm@kuberlogic.com"
        emailVerified: False
        credentials:
          - type: password
            value: {{ .Values.realm.adminPassword }}
            temporary: false
        realmRoles:
          - "offline_access"
          - "uma_authorization"
          - "uma_protection"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
          realm-management:
            - "manage-users"
            - "view-users"
            - "query-users"
            - "create-client"
  instanceSelector:
    matchLabels:
  {{ toYaml .Values.labels | nindent 6 }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
  labels:
  {{ toYaml .Values.labels | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
  {{ toYaml .Values.labels | nindent 6 }}
  client:
    clientId: {{ .Values.clientId }}
    secret: {{ .Values.clientSecret }}
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    authorizationServicesEnabled: {{ .Values.authorization.enabled }}
    authorizationSettings:
      allowRemoteResourceManagement: true
      resources:
        - name: "*"
          type: kuberlogicservice
          scopes:
            - name: "service:*"
{{ if .Values.testUser.create }}
        - name: "4f6b97e729327473139acd2748457f44:*"
          type: kuberlogicservice
          scopes:
            - name: "service:*"
{{ end }}
      policies:
{{ if .Values.testUser.create }}
        - name: kuberlogic-test-user-allow
          type: user
          logic: POSITIVE
          config:
            users: '["kuberlogic-test-user"]'
        - name: kuberlogic-test-user-full
          type: scope
          decisionStrategy: UNANIMOUS
          config:
            applyPolicies: '["kuberlogic-test-user-allow"]'
            scopes: '["service:*"]'
            resources: '["4f6b97e729327473139acd2748457f44:*"]'
{{ end }}
        - name: kuberlogic-system-allow
          type: user
          logic: POSITIVE
          config:
            users: '["{{ .Values.realm.name }}"]'
        - name: kuberlogic-system-full
          type: scope
          decisionStrategy: UNANIMOUS
          config:
            applyPolicies: '["kuberlogic-system-allow"]'
            scopes: '["service:*"]'
            resources: '["*"]'
    protocolMappers:
      - name: "apiserver-aud"
        protocol: "openid-connect"
        consentRequired: false
        protocolMapper: "oidc-audience-mapper"
        config:
          included.client.audience: "{{ .Values.clientId }}"
          access.token.claim: "true"
    defaultRoles:
    - "uma_protection"
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - email
      - profile
      - roles
      - offline_access
      - web-origins
{{ if .Values.testUser.create }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: kuberlogic-test-user
  labels:
  {{ toYaml .Values.labels | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
  {{ toYaml .Values.labels | nindent 6 }}
  user:
    credentials:
      - type: password
        value: {{ .Values.testUser.password }}
        temporary: false
    email: keycloak@example.com
    id: kuberlogic-test-user
    username: kuberlogic-test-user
    enabled: true
    firstName: Sample
    lastName: User
    realmRoles:
      - "offline_access"
      - "uma_authorization"
    clientRoles:
      account:
        - manage-account
        - view-profile
{{ end }}